weather_center/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather_report.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

weather_report/urls.py
from django.urls import path

from . import views

app_name = 'weather_report'

urlpatterns = [
    path('', views.index, name='home'),
    path('city/', views.detail, name='weather-detail'),
]

weather_report/models.py
from django.db import models

# Create your models here.

weather_report/forms.py
import pytz

from django import forms

sorted_country_list = sorted(pytz.country_names.items(), key=lambda item: item[1])


class AdvancedSearchForm(forms.Form):
    country = forms.ChoiceField(choices=sorted_country_list)
    city = forms.CharField(max_length=128)

weather_report/views.py
from django.shortcuts import render
from django.http import Http404
from django.conf import settings

from .weather import get_current_city_weather_data, get_five_days_forecast
from .forms import AdvancedSearchForm
from .google_api import GoogleMapsClient


def index(request):
    data = {}
    for city in ['harbin', 'montreal', 'san diego']:
        query_str = 'http://api.openweathermap.org/data/2.5/weather?q={}&units=metric&appid={}'.format(city,
                                                                                                       settings.WEATHER_API_KEY)
        data[city.split()[0] + '_report'] = get_current_city_weather_data(query_str)
    return render(request,
                  'weather_report/index.html',
                  {'data': data})


def detail(request):
    if request.method == "POST":
        location = None
        city = request.POST.get('city', None)
        country_code = request.POST.get('country', None)
        if country_code is not None:
            location = ','.join([city, country_code])
        else:
            location = city
        client = GoogleMapsClient(api_key=settings.GOOGLE_API_KEY, address_or_zip=location)

        # construct two query strings for weather API
        current_query_str = 'http://api.openweathermap.org/data/2.5/weather?lat={}&lon={}&units=metric&appid={}'.format(
            client.lat, client.lng, settings.WEATHER_API_KEY)
        trend_query_str = 'http://api.openweathermap.org/data/2.5/forecast?lat={}&lon={}&units=metric&appid={}'.format(
            client.lat, client.lng, settings.WEATHER_API_KEY)

        # construct query string for embed Google Map
        embed_map_query_str = "https://www.google.com/maps/embed/v1/place?key={}&q={}".format(settings.GOOGLE_API_KEY,
                                                                                              location)

        # retrieve single point report and trend chart
        current_report = get_current_city_weather_data(current_query_str)
        trend_report = get_five_days_forecast(trend_query_str)
        if current_report['cod'] == 404:
            raise Http404()

        restaurants = client.get_top_5_places()

        city = city.title()

        return render(request, 'weather_report/detail.html',
                      {'current_report': current_report, 'trend_report': trend_report, 'city': city,
                       'embed_map_query_str': embed_map_query_str, 'restaurants': restaurants})
    else:
        form = AdvancedSearchForm()
    return render(request, 'weather_report/advanced_search_modal.html', {'form': form})

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        {% block page_title %}{% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}">

    {% block site_css %}
        <link rel="stylesheet" type="text/css" media="all" href="{% static 'css/style.css' %}"/>
    {% endblock %}

    {% block extra_head %}
        {# Extra header stuff (scripts, styles, metadata, etc) #}
    {% endblock %}
</head>

<body>
<div class="modal fade" id="pgModal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
        </div>
    </div>
</div>

<nav class="navbar justify-content-center navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'weather_report:home' %}">Weather Forecast </a>
</nav>

<div class="container-fluid">
    {% block content %}{% endblock %}
</div>


{# Page javascript #}
{% autoescape off %}
    {% block page_js %}
    {% endblock %}
{% endautoescape %}
</body>

templates/modal_base.html
<form action="{% block body_action %}{% endblock %}" method="post">
    {% csrf_token %}
    <div class="modal-header">
        <h5 class="modal-title">{% block modal_title %}{% endblock %}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
        </button>
    </div>

    <div class="modal-body">
        {% block modal_body %}{% endblock %}
    </div>

    <div class="modal-footer">
        <button type="submit" class="btn btn-primary">Search</button>
    </div>
</form>

weather_report/templates/weather_report/advanced_search_modal.html
{% extends 'modal_base.html' %}

{% block body_action %}{% url 'weather_report:weather-detail' %}{% endblock %}

{% block modal_title %}Advanced Search{% endblock %}

{% block modal_body %}
    {{ form.as_p }}
{% endblock %}

weather_report/templates/weather_report/detail.html
{% extends 'base.html' %}

{% block page_title %}
    Weather Detail
{% endblock %}

{% block extra_head %}
    <style>
        img.resize {
            width: 800px;
            height: auto;
            max-width: 100%;
            max-height: 100%;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="row g-5">
        <div class="col-sm-6 p-5">
            <div class="row">
                <h5>{{ current_report.local_time }}</h5>
                <h1>{{ city }}, {{ current_report.country }}</h1>
                <table class="table">
                    <tbody>
                    <tr>
                        <th scope="row">Weather:</th>
                        <td>{{ current_report.weather }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Temperature:</th>
                        <td>{{ current_report.temp }}<span>&#8451;</span></td>
                    </tr>
                    <tr>
                        <th scope="row">Feels like:</th>
                        <td>{{ current_report.feels_like }}<span>&#8451;</span></td>
                    </tr>
                    <tr>
                        <th scope="row">Wind:</th>
                        <td>{{ current_report.wind }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Sunrise:</th>
                        <td>{{ current_report.sun_rise_local }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Sunset:</th>
                        <td>{{ current_report.sun_set_local }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="row">
                <div class="border bg-light">
                    <img class="resize" src="data:image/png;base64,{{ trend_report.chart|safe }}" alt="">
                </div>
            </div>

        </div>

        <div class="col-sm-6">
            <div class="row p-3 border bg-ligh">
                <iframe
                        title="embed map"
                        width="100%"
                        height="450"
                        style="border:0"
                        src={{ embed_map_query_str }}
                                allowfullscreen>
                </iframe>
            </div>

            <div class="row p-3 border bg-ligh">
                <h5>Top Chinese Restaurants</h5>
                {% if restaurants %}
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Address</th>
                            <th scope="col">Phone#</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for r in restaurants %}
                            <tr>
                                <td>{{ r.name }}</td>
                                <td>{{ r.formatted_address }}</td>
                                <td>{{ r.formatted_phone_number }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <h6>Sorry, there is no Chinese restaurants around this area.</h6>
                {% endif %}
            </div>

        </div>
    </div>
{% endblock %}

weather_report/templates/weather_report/index.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
    Weather Center
{% endblock %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="{% static 'weather_report/report.css' %}"/>
{% endblock %}

{% block content %}
    <div class="row d-flex align-items-center justify-content-center">
        <div class="col-md-6">

            <form method="post" action="{% url 'weather_report:weather-detail' %}">
                {% csrf_token %}
                <div class="form">
                    <i class="fa fa-search"></i>
                    <input type="text" name="city" class="form-control form-input" placeholder="Search City...">
                    <button type="button" class="btn btn-advance-search" id="advanced-search"
                            data-url="{% url 'weather_report:weather-detail' %}">
                        Advanced
                    </button>
                </div>
            </form>
        </div>

        <div class="row row-cols-1 row-cols-md-3 g-5">
            <div class="col">
                <div class="card h-100">
                    <div class="card-body">
                        <div class="card-title">
                            <form method='post' action="{% url 'weather_report:weather-detail' %}">
                                {% csrf_token %}
                                <input type='submit' name='city' value='Harbin'>
                            </form>
                        </div>
                        <table class="table">
                            <tbody>
                            <tr>
                                <th scope="row">Weather:</th>
                                <td>{{ data.harbin_report.weather }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Temperature:</th>
                                <td>{{ data.harbin_report.temp }}<span>&#8451;</span></td>
                            </tr>
                            <tr>
                                <th scope="row">Feels like:</th>
                                <td>{{ data.harbin_report.feels_like }}<span>&#8451;</span></td>
                            </tr>
                            <tr>
                                <th scope="row">Wind:</th>
                                <td>{{ data.harbin_report.wind }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Sunrise:</th>
                                <td>{{ data.harbin_report.sun_rise_local }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Sunset:</th>
                                <td>{{ data.harbin_report.sun_set_local }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <div id="china_clock"></div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <div class="card-body">
                        <div class="card-title">
                            <form method='post' action="{% url 'weather_report:weather-detail' %}">
                                {% csrf_token %}
                                <input type='submit' name='city' value='Montreal'>
                            </form>
                        </div>

                        <table class="table">
                            <tbody>
                            <tr>
                                <th scope="row">Weather:</th>
                                <td>{{ data.montreal_report.weather }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Temperature:</th>
                                <td>{{ data.montreal_report.temp }}<span>&#8451;</span></td>
                            </tr>
                            <tr>
                                <th scope="row">Feels like:</th>
                                <td>{{ data.montreal_report.feels_like }}<span>&#8451;</span></td>
                            </tr>
                            <tr>
                                <th scope="row">Wind:</th>
                                <td>{{ data.montreal_report.wind }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Sunrise:</th>
                                <td>{{ data.montreal_report.sun_rise_local }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Sunset:</th>
                                <td>{{ data.montreal_report.sun_set_local }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <div id="east_clock"></div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <div class="card-body">
                        <div class="card-title">
                            <form method='post' action="{% url 'weather_report:weather-detail' %}">
                                {% csrf_token %}
                                <input type='submit' name='city' value='San Diego'>
                            </form>
                        </div>

                        <table class="table">
                            <tbody>
                            <tr>
                                <th scope="row">Weather:</th>
                                <td>{{ data.san_report.weather }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Temperature:</th>
                                <td>{{ data.san_report.temp }}<span>&#8451;</span></td>
                            </tr>
                            <tr>
                                <th scope="row">Feels like:</th>
                                <td>{{ data.san_report.feels_like }}<span>&#8451;</span></td>
                            </tr>
                            <tr>
                                <th scope="row">Wind:</th>
                                <td>{{ data.san_report.wind }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Sunrise:</th>
                                <td>{{ data.san_report.sun_rise_local }}</td>
                            </tr>
                            <tr>
                                <th scope="row">Sunset:</th>
                                <td>{{ data.san_report.sun_set_local }}</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer">
                        <div id="west_clock"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block page_js %}
    <script src="{% static 'weather_report/report.js' %}"></script>
{% endblock %}